### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by zabujka** [zabujka/Susi#4] opened 2020-10-13 09:31 UTC
Footer

**Comment by zabujka** [comment] 2020-10-13 09:35
The div in the footer 

1. How do i position the buttons within the div to have them all in one row? 
2. Button Phone: Can we make an option ´call this number´ when click on the phone number button? 
3. Button: Adress: on click open the google map with the address

**Comment by annarogala** [comment] 2020-10-14 18:48
Just to say, an assignee (or assignees if it is a "pair-programming") in an issue is a developer who works on it. That would be mostly you :)
Where I need you to assign me is just the Pull Request you want me to check.

**Comment by annarogala** [comment] 2020-10-14 18:52
When you open an issue (kudos on that :D ), plesae, meka sure its title descripbes what there is to do, what the problem is or what functionality you want to intorduce, eg. Issue # 5 can be titled: "Position the buttons within the div to have them all in one row", issue #6: "Add ´call this number´ when click on the phone number button" (if you are not sure if this is doable, just write your concerns in the issue's description), issue #7: "Add google map with the address on click".
Please, close this issue and open three new ones as listed above.

Issues are tasks to do. Not notes ;)
If you need a place for notes we should start using Projects tab - I promise I will fix a project for us as soon as I can :)

**Closed as completed** 2020-10-29 14:32 UTC
